### PR TITLE
moving oauth scopes to variable

### PR DESCRIPTION
**Pull request by mike-ensor**
Moving the explicitly written oauth scopes into a variable so projects using this module can override the oauth scopes if needed

### CODE REVIEW

**Comment by morgante** [comment]
@mike-ensor I'm skeptical we should actually make this a variable. IMO it'd be better to switch to the generalized cloud-platform scope as scopes are generally not a reliable control mechanism anyways.

**Comment by mike-ensor** [comment]
@morgante I can do that, I was trying to keep "as-is" for now, then let someone make the decision to change away from scopes all together (workload-identity, if possible with the helm chart).  My use case requires that I use "https://www.googleapis.com/auth/cloud-platform" scope. I am trying to access secrets and the GSA + current scopes do not work, I need to use cloud-platform.

Let me know which you'd like. Keep as-is meaning future work (I can create an issue now) or just update the scopes to the "cloud-platform" all-scopes now.

**Comment by morgante** [comment]
@mike-ensor Got it, I think let's just make the switch now.

@viglesiasce Any objection to switching to `cloud-platform`?

**Comment by mike-ensor** [comment]
I've changed the code back to just modifying the oAuth scopes, and to only use the "cloud-platform" which is the "all scopes"

**Comment by viglesiasce** [comment]
cloud-platform scope 👍

**Pull request merged**
